{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOpenldap" "appNameSuffix" "") -}}
{{- $openldap := .Values.services.openldap }}
{{- if $openldap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .appName }}-config
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    {{- include "oc.labels" . | nindent 4 }}
data:
  10_opencloud_schema.ldif: |-
{{ .Files.Get "files/openldap/schemas/10_opencloud_schema.ldif" | nindent 4 }}
  10_base.ldif: |-
{{ .Files.Get "files/openldap/ldif/10_base.ldif" | nindent 4 }}
{{- end }}
