{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOpenldap" "appNameSuffix" "") -}}
{{- $openldap := .Values.services.openldap }}
{{- if and $openldap.enabled $openldap.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .appName }}-data
  namespace: {{ template "oc.namespace" . }}
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    app: {{ .appName }}
    {{- include "oc.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $openldap.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ $openldap.persistence.size | quote }}
  {{- if $openldap.persistence.storageClass }}
  {{- if (eq "-" $openldap.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ $openldap.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
