{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOpenldap" "appNameSuffix" "") -}}
{{- $openldap := .Values.services.openldap }}
{{- if and $openldap.enabled (not .Values.secretRefs.ldapSecretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    {{- include "oc.labels" . | nindent 4 }}
type: Opaque
stringData:
  adminPassword: {{ $openldap.adminPassword }}
{{- end }}
