{{- if and .Values.ldap.enabled (not .Values.secretRefs.ldapSecretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.openldap.fullname" . }}
  labels:
    app.kubernetes.io/component: openldap
type: Opaque
stringData:
  adminPassword: {{ .Values.ldap.adminPassword }}
{{- end }}