{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameOpenldap" "appNameSuffix" "") -}}
{{- $openldap := .Values.services.openldap }}
{{- if $openldap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "oc.namespace" . }}
  labels:
    app: {{ .appName }}
    {{- include "oc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .appName }}
  ports:
    - port: 1389
      targetPort: ldap
      protocol: TCP
      name: ldap
    - port: 1636
      targetPort: ldaps
      protocol: TCP
      name: ldaps
{{- end }}
