{{- $_ := set . "ldapCA" (genCA "ldap-ca" 365) }}
{{ if and (not .Values.secretRefs.ldapCaRef) (not .Values.features.externalUserManagement.enabled)  }}
{{- $params := (dict)}}
{{- $_ := set $params "ldap-ca.crt" .ldapCA.Cert }}
{{- include "oc.secret" (dict "scope" . "name" "ldap-ca" "params" $params)}}
{{- end }}
---
{{ if and (not .Values.secretRefs.ldapCertRef) (not .Values.features.externalUserManagement.enabled)  }}
{{- $params := (dict)}}
{{- $ldapCert := genSignedCert "idm" nil (list "idm") 365  .ldapCA }}
{{- $_ := set $params "ldap.key" $ldapCert.Key }}
{{- $_ := set $params "ldap.crt" $ldapCert.Cert }}
{{- include "oc.secret" (dict "scope" . "name" "ldap-cert" "params" $params)}}
{{- end }}
---
{{ if not .Values.secretRefs.ldapSecretRef }}
{{- $params := (dict)}}
{{- if and .Values.features.externalUserManagement.enabled .Values.services.openldap.enabled }}
{{- $_ := set $params "reva-ldap-bind-password" (default (randAlphaNum 30) .Values.services.openldap.adminPassword) }}
{{- else }}
{{- $_ := set $params "reva-ldap-bind-password" (randAlphaNum 30) }}
{{- end }}
{{- $_ := set $params "idp-ldap-bind-password" (randAlphaNum 30) }}
{{- $_ := set $params "graph-ldap-bind-password" (randAlphaNum 30) }}
{{- include "oc.secret" (dict "scope" . "name" "ldap-bind-secrets" "labels" .Values.backup.secretLabels "params" $params)}}
{{- end }}
